Funeral Policy/Models/AssignStaff.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IdentitySample.Models;

namespace Funeral_Policy.Models
{
    public class AssignStaff
    {
        [Key]
        public int AssignId { get; set; }

        public int StaffId { get; set; }
        public virtual Staff Staff { get; set; }
        [DisplayName("order Number")]
        public int funeralBookingId { get; set; }
        public string Member { get; set; }
        public string Coffin { get; set; }
        [DisplayName("Funeral Type")]
        public string FuneralType { get; set; }
        [DisplayName("Funeral Date")]
        public DateTime FuneraralDate { get; set; }
        [DisplayName("Funeral Address")]
        public string adress { get; set; }
        ApplicationDbContext db = new ApplicationDbContext();
        public string user()
        {
            var u = (from s in db.FuneralBookings
                     where s.funeralBookingId == funeralBookingId
                     select s.creator).FirstOrDefault();
            return u;
        }
        public string Coffins()
        {
            var u = (from s in db.FuneralBookings
                     where s.funeralBookingId == funeralBookingId
                     select s.CoffinName).FirstOrDefault();
            return u;
        }
        public string funeralTypes()
        {
            var u = (from s in db.FuneralBookings
                     where s.funeralBookingId == funeralBookingId
                     select s.FuneralName).FirstOrDefault();
            return u;
        }
        public string FuneralAddress()
        {
            var j = (from s in db.FuneralBookings
                     where s.funeralBookingId == funeralBookingId
                     select s.address).FirstOrDefault();
            return j;
        }

        public DateTime Date()
        {
            var d = (from s in db.FuneralBookings
                     where s.funeralBookingId == funeralBookingId
                     select s.FuneralDate).FirstOrDefault();
            return d;
        }
        public string FuneralName()
        {
            var z = (from s in db.FuneralBookings
                     where s.funeralBookingId == funeralBookingId
                     select s.FuneralName).FirstOrDefault();
            return z;
        }
    }
}

Funeral Policy/Controllers/AssignStaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Funeral_Policy.Models;
using IdentitySample.Models;

namespace Funeral_Policy.Controllers
{
    public class AssignStaffsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AssignStaffs
        public ActionResult Index()
        {
            var assignStaffs = db.AssignStaffs.Include(a => a.Staff);
            return View(assignStaffs.ToList());
        }
        public ActionResult Index2()
        {
            var assignStaffs = db.AssignStaffs.Include(a => a.Staff);
            return View(assignStaffs.ToList());
        }

        // GET: AssignStaffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AssignStaff assignStaff = db.AssignStaffs.Find(id);
            if (assignStaff == null)
            {
                return HttpNotFound();
            }
            return View(assignStaff);
        }

        // GET: AssignStaffs/Create
        public ActionResult Create(int id)
        {
            ViewBag.Id = id;
            AssignStaff assignStaff = new AssignStaff();
            assignStaff.funeralBookingId = id;
            ViewBag.StaffId = new SelectList(db.Staffs, "StaffId", "Name");
            return View(assignStaff);
        }

        // POST: AssignStaffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AssignId,StaffId,funeralBookingId")] AssignStaff assignStaff)
        {
            if (ModelState.IsValid)
            {
                var d = db.FuneralBookings.Where(p => p.funeralBookingId == assignStaff.funeralBookingId).FirstOrDefault();
                d.Status = "Approved";
                assignStaff.Member = assignStaff.user();
                assignStaff.FuneralType = assignStaff.funeralTypes();
                assignStaff.Coffin = assignStaff.Coffins();
                assignStaff.FuneraralDate = assignStaff.Date();
                assignStaff.adress = assignStaff.FuneralAddress();
                db.AssignStaffs.Add(assignStaff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StaffId = new SelectList(db.Staffs, "StaffId", "Name", assignStaff.StaffId);
            return View(assignStaff);
        }

        // GET: AssignStaffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AssignStaff assignStaff = db.AssignStaffs.Find(id);
            if (assignStaff == null)
            {
                return HttpNotFound();
            }
            ViewBag.StaffId = new SelectList(db.Staffs, "StaffId", "Name", assignStaff.StaffId);
            return View(assignStaff);
        }

        // POST: AssignStaffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AssignId,StaffId,funeralBookingId")] AssignStaff assignStaff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(assignStaff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StaffId = new SelectList(db.Staffs, "StaffId", "Name", assignStaff.StaffId);
            return View(assignStaff);
        }

        // GET: AssignStaffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AssignStaff assignStaff = db.AssignStaffs.Find(id);
            if (assignStaff == null)
            {
                return HttpNotFound();
            }
            return View(assignStaff);
        }

        // POST: AssignStaffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AssignStaff assignStaff = db.AssignStaffs.Find(id);
            db.AssignStaffs.Remove(assignStaff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Funeral Policy/Views/AssignStaffs/Create.cshtml
@model Funeral_Policy.Models.AssignStaff

@{
    ViewBag.Title = "Create";
}

<h2>Assign Staff</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @*<h4>AssignStaff</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.funeralBookingId)

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.StaffId, "Staff Names", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StaffId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StaffId, "", new { @class = "text-danger" })
        </div>
    </div>



    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Assign Staff" class="btn btn-dark" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Funeral Policy/Views/AssignStaffs/Delete.cshtml
@model Funeral_Policy.Models.AssignStaff

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AssignStaff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staff.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.funeralBookingId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.funeralBookingId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Member)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coffin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coffin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FuneralType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuneralType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Funeral Policy/Views/AssignStaffs/Details.cshtml
@model Funeral_Policy.Models.AssignStaff

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AssignStaff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staff.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.funeralBookingId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.funeralBookingId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Member)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coffin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coffin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FuneralType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuneralType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AssignId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Funeral Policy/Views/AssignStaffs/Edit.cshtml
@model Funeral_Policy.Models.AssignStaff

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AssignStaff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AssignId)

        <div class="form-group">
            @Html.LabelFor(model => model.StaffId, "StaffId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StaffId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StaffId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.funeralBookingId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.funeralBookingId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.funeralBookingId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Member, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Member, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Member, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coffin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coffin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Coffin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FuneralType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FuneralType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FuneralType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Funeral Policy/Views/AssignStaffs/Index.cshtml
@model IEnumerable<Funeral_Policy.Models.AssignStaff>

@{
    ViewBag.Title = "Index";
}

<html>
<head>

    <style>
        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 1.2em;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }
    </style>

</head>
<body>
    <center>

        <div style="background-color:whitesmoke; height:37px;width:85% ;font-size:15px;">
            <h2>Assigned Staff</h2>
        </div>
        <div class="card shadow mb-4" style="background-color:aliceblue;height:max-content; width:max-content;font-size:13px; top:auto">
            <div class="card-header ">


                @*<p>
                        @Html.ActionLink("Create New", "Create")
                    </p>*@
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Staff.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.funeralBookingId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Member)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Coffin)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FuneralType)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.adress)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Staff.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.funeralBookingId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Member)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Coffin)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FuneralType)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.adress)
                            </td>


                            <td>
                                <a href="@Url.Action("Details","AssignStaffs", new { id=item.AssignId })" rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs">Details<i class="fa fa-eye"></i></a>
                                <a href="@Url.Action("Edit","AssignStaffs", new { id=item.AssignId })" rel="tooltip" title="Edit" class="btn btn-success btn-simple btn-xs">Edit<i class="fa fa-edit"></i></a>
                                <a href="@Url.Action("Delete", "AssignStaffs", new { id = item.AssignId })" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">Delete<i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>

    </center>



</body>
</html>