Funeral Policy/Controllers/CartController/ShoppingController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Funeral_Policy.Models.CartModels;
using Funeral_Policy.Services.CartServices;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Funeral_Policy.Models;

namespace Funeral_Policy.Controllers.CartController
{
    public class ShoppingController : Controller
    {
        private Cart_Service cart_Service;
        private Item_Service item_Service;
        private Order_Service order_Service;
        private Address_Service address_Service;
        Category_Service Category_Service;
        private ApplicationDbContext db = new ApplicationDbContext();

        public ShoppingController()
        {
            this.cart_Service = new Cart_Service();
            this.item_Service = new Item_Service();
            this.order_Service = new Order_Service();
            this.address_Service = new Address_Service();
            this.Category_Service = new Category_Service();
        }
        public ActionResult Index(int? id)
        {
            var items_results = new List<Item>();
            try
            {
                if (id != null)
                {
                    if (id == 0)
                    {
                        items_results = item_Service.GetItems();
                        ViewBag.Department = "All Categories";
                    }
                    else
                    {
                        items_results = item_Service.GetItems().Where(x => x.Category_ID == (int)id).ToList();
                        ViewBag.Department = Category_Service.GetCategory(id).Name;
                    }
                }
                else
                {
                    items_results = item_Service.GetItems();
                    ViewBag.Department = "All Categories";
                }
            }
            catch (Exception ex) { }
            return View(items_results);
        }
        public ActionResult add_to_cart(int id)
        {
            var UserName = User.Identity.GetUserName();
            int qty = 1;
            var item = item_Service.GetItem(id);

            Cart_Item ct = new Cart_Item();

            if (item != null)
            {
                cart_Service.UpdateQuantity(id, qty);
                cart_Service.AddItemToCart(id, UserName);
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult remove_from_cart(string id)
        {
            var item = cart_Service.GetCartItems().FirstOrDefault(x => x.cart_item_id == id);
            if (item != null)
            {

                cart_Service.RemoveItemFromCart(id: id);
                return RedirectToAction("ShoppingCart");
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult ShoppingCart()
        {
            ViewBag.Total = cart_Service.GetCartTotal(cart_Service.GetCartID());
            ViewBag.TotalQTY = cart_Service.GetCartItems().FindAll(x => x.cart_id == cart_Service.GetCartID()).Sum(q => q.quantity);
            return View(cart_Service.GetCartItems().FindAll(x => x.cart_id == cart_Service.GetCartID()));
        }
        [HttpPost]
        public ActionResult ShoppingCart(List<Cart_Item> items)
        {
            foreach (var i in items)
            {
                cart_Service.UpdateCart(i.cart_item_id, i.quantity);
            }
            return RedirectToAction("ShoppingCart");
        }
        public ActionResult countCartItems()
        {
            var username = User.Identity.GetUserName();
            int qty = cart_Service.GetCartItems().Sum(x => x.quantity);
            return Content(qty.ToString());
        }
        public ActionResult Checkout()
        {
            FuneralBooking c = new FuneralBooking();
            if (cart_Service.GetCartItems().Count == 0)
            {
                ViewBag.Err = "Opps... you should have atleat one cart item, please shop a few items";
                return RedirectToAction("Index");
            }
            else
                cart_Service.EmptyCart();
            cart_Service.checkout(User.Identity.Name);
            return RedirectToAction("Index", "FuneralBookings");

        }
        [Authorize]
        public ActionResult HowToGetMyOrder()
        {
            return View();
        }
        [HttpPost]
        public ActionResult HowToGetMyOrder(string street_number, string street_name, string City, string State, string ZipCode, string Country)
        {
            Session["street_number"] = street_number;
            Session["street_name"] = street_name;
            Session["City"] = City;
            Session["State"] = State;
            Session["ZipCode"] = ZipCode;
            Session["Country"] = Country;
            return RedirectToAction("PlaceOrder", new { id = "deliver" });
        }

    }
}

Funeral Policy/Controllers/PaymentController.cs
//using PayFast;
using PayFast.AspNet;
using System.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayFast;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using Funeral_Policy.Models.CartModels;
using Microsoft.AspNet.Identity;
using System.Net.Mail;
using Funeral_Policy.Services.CartServices;
using Funeral_Policy.Models;
using Funeral_Policy.Services;
using System.Data.Entity;
using IdentitySample.Models;

namespace Funeral_Policy.Controllers
{
    public class PaymentController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private Order_Service order_Service;



        // GET: Payment
        public ActionResult Index()
        {
            return View();
        }

        private readonly PayFastSettings payFastSettings;

        #region Constructor

        public PaymentController()
        {
            this.payFastSettings = new PayFastSettings
            {
                MerchantId = ConfigurationManager.AppSettings["MerchantId"],
                MerchantKey = ConfigurationManager.AppSettings["MerchantKey"],
                PassPhrase = ConfigurationManager.AppSettings["PassPhrase"],
                ProcessUrl = ConfigurationManager.AppSettings["ProcessUrl"],
                ValidateUrl = ConfigurationManager.AppSettings["ValidateUrl"],
                ReturnUrl = ConfigurationManager.AppSettings["ReturnUrl"],
                CancelUrl = ConfigurationManager.AppSettings["CancelUrl"],
                NotifyUrl = ConfigurationManager.AppSettings["NotifyUrl"]
            };
            order_Service = new Order_Service();

        }

        #endregion Constructor

        #region Methods



        public ActionResult Recurring()
        {

            var recurringRequest = new PayFastRequest(this.payFastSettings.PassPhrase);

            // Merchant Details
            recurringRequest.merchant_id = this.payFastSettings.MerchantId;
            recurringRequest.merchant_key = this.payFastSettings.MerchantKey;
            recurringRequest.return_url = this.payFastSettings.ReturnUrl;
            recurringRequest.cancel_url = this.payFastSettings.CancelUrl;
            recurringRequest.notify_url = this.payFastSettings.NotifyUrl;

            // Buyer Details
            recurringRequest.email_address = "sbtu01@payfast.co.za";

            // Transaction Details
            recurringRequest.m_payment_id = "8d00bf49-e979-4004-228c-08d452b86380";
            recurringRequest.amount = 20;
            recurringRequest.item_name = "Recurring Option";
            recurringRequest.item_description = "Some details about the recurring option";

            // Transaction Options
            recurringRequest.email_confirmation = true;
            recurringRequest.confirmation_address = "drnendwandwe@gmail.com";

            // Recurring Billing Details
            recurringRequest.subscription_type = SubscriptionType.Subscription;
            recurringRequest.billing_date = DateTime.Now;
            recurringRequest.recurring_amount = 20;
            recurringRequest.frequency = BillingFrequency.Monthly;
            recurringRequest.cycles = 0;

            var redirectUrl = $"{this.payFastSettings.ProcessUrl}{recurringRequest.ToString()}";

            return Redirect(redirectUrl);
        }     

        public ActionResult OnceOff(double payment, int id)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            var ordr = db.FuneralBookings.Where(p => p.funeralBookingId == id).Select(p => p.isPaid).FirstOrDefault();
            ordr = true;

            var onceOffRequest = new PayFastRequest(this.payFastSettings.PassPhrase);
            //var callbackUrl = Url.Action("Create", "Parents",null, protocol: Request.Url.Scheme);
            var callbackUrl = Url.Action("Return", "Payment", payment);
            //var order = order_Service.GetOrder(id);
            //var onceOffRequest = new PayFastRequest(this.payFastSettings.PassPhrase);
            FuneralBooking order1 = db.FuneralBookings.Find(id);
            order1.Status = "Paid";
            db.Entry(order1).State = EntityState.Modified;
            db.SaveChanges();
            //var order=
            // Merchant Details
            onceOffRequest.merchant_id = this.payFastSettings.MerchantId;
            onceOffRequest.merchant_key = this.payFastSettings.MerchantKey;
            onceOffRequest.return_url = this.payFastSettings.ReturnUrl;
            onceOffRequest.cancel_url = this.payFastSettings.CancelUrl;
            onceOffRequest.notify_url = this.payFastSettings.NotifyUrl;

            // Buyer Details
            onceOffRequest.email_address = "sbtu01@payfast.co.za";
            //double amount = Convert.ToDouble(db.Items.Select(x => x.CostPrice).FirstOrDefault());
            //var products = db.Items.Select(x => x.Name).ToList();
            // Transaction Details
            var userName = User.Identity.GetUserName();
            onceOffRequest.m_payment_id = "";
            onceOffRequest.amount = payment;
            ///onceOffRequest.amount = order_Service.GetOrderTotal(order.Order_ID);
            onceOffRequest.item_name = "Funeral Total Cost";
            onceOffRequest.item_description = "Some details about the once off payment";


            // Transaction Options
            onceOffRequest.email_confirmation = true;
            onceOffRequest.confirmation_address = "sbtu01@payfast.co.za";

            var redirectUrl = $"{this.payFastSettings.ProcessUrl}{onceOffRequest.ToString()}";

            return Redirect(redirectUrl);
        }

        public ActionResult AdHoc()
        {
            var adHocRequest = new PayFastRequest(this.payFastSettings.PassPhrase);

            // Merchant Details
            adHocRequest.merchant_id = this.payFastSettings.MerchantId;
            adHocRequest.merchant_key = this.payFastSettings.MerchantKey;
            adHocRequest.return_url = this.payFastSettings.ReturnUrl;
            adHocRequest.cancel_url = this.payFastSettings.CancelUrl;
            adHocRequest.notify_url = this.payFastSettings.NotifyUrl;
            #endregion Methods
            // Buyer Details
            adHocRequest.email_address = "sbtu01@payfast.co.za";
            //double amount = Convert.ToDouble(db.FoodOrders.Select(x => x.Total).FirstOrDefault());
            //var products = db.FoodOrders.Select(x => x.UserEmail).ToList();
            // Transaction Details
            adHocRequest.m_payment_id = "";
            adHocRequest.amount = 70;
            adHocRequest.item_name = "Adhoc Agreement";
            adHocRequest.item_description = "Some details about the adhoc agreement";

            // Transaction Options
            adHocRequest.email_confirmation = true;
            adHocRequest.confirmation_address = "sbtu01@payfast.co.za";

            // Recurring Billing Details
            adHocRequest.subscription_type = SubscriptionType.AdHoc;

            var redirectUrl = $"{this.payFastSettings.ProcessUrl}{adHocRequest.ToString()}";

            return Redirect(redirectUrl);
        }

        public ActionResult Return()
        {
            return View();
        }

        public ActionResult Cancel()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Notify([ModelBinder(typeof(PayFastNotifyModelBinder))] PayFastNotify payFastNotifyViewModel)
        {
            payFastNotifyViewModel.SetPassPhrase(this.payFastSettings.PassPhrase);

            var calculatedSignature = payFastNotifyViewModel.GetCalculatedSignature();

            var isValid = payFastNotifyViewModel.signature == calculatedSignature;

            System.Diagnostics.Debug.WriteLine($"Signature Validation Result: {isValid}");

            // The PayFast Validator is still under developement
            // Its not recommended to rely on this for production use cases
            var payfastValidator = new PayFastValidator(this.payFastSettings, payFastNotifyViewModel, IPAddress.Parse(this.HttpContext.Request.UserHostAddress));

            var merchantIdValidationResult = payfastValidator.ValidateMerchantId();

            System.Diagnostics.Debug.WriteLine($"Merchant Id Validation Result: {merchantIdValidationResult}");

            var ipAddressValidationResult = payfastValidator.ValidateSourceIp();

            System.Diagnostics.Debug.WriteLine($"Ip Address Validation Result: {merchantIdValidationResult}");

            // Currently seems that the data validation only works for successful payments
            if (payFastNotifyViewModel.payment_status == PayFastStatics.CompletePaymentConfirmation)
            {
                var dataValidationResult = await payfastValidator.ValidateData();

                System.Diagnostics.Debug.WriteLine($"Data Validation Result: {dataValidationResult}");
            }

            if (payFastNotifyViewModel.payment_status == PayFastStatics.CancelledPaymentConfirmation)
            {
                System.Diagnostics.Debug.WriteLine($"Subscription was cancelled");
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

Funeral Policy/Views/Shopping/HowToGetMyOrder.cshtml
@{ ViewBag.Title = "How would you like to receive your order?"; }

<h2 class="title text-center">@ViewBag.Title</h2>

<form method="post">
    <div class="row">
        <div class="board">
            <!-- <h2>Welcome to IGHALO!<sup>™</sup></h2>-->
            <div class="board-inner">
                <ul class="nav nav-tabs" id="myTab">
                    <li class="active" style="text-align:center">
                        <a href="#home" data-toggle="tab" title="Collect at warehouse">
                            <span class="round-tabs">
                                <i class="fa fa-home"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#profile" data-toggle="tab" title="Standard Delivery">
                            <span class="round-tabs">
                                <i class="fa fa-truck"></i>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade in active" id="home">
                    <h4 class="head text-center">Collect your order at our warehouse.</h4>
                    <h4> <i class="fa fa-map-marker"></i>  123 Sept St, Durban, 4001 </h4>
                    <h4> <i class="fa fa-clock-o"></i>  Monday - Friday</h4>
                    <h4> <i class="fa fa-clock-o"></i>  8:30 am - 17:00 pm working hours</h4>
                    <a href="@Url.Action("PlaceOrder","Shopping", new {id = "collect" })" class="btn btn-default"> Continue</a>
                </div>
                <div class="tab-pane fade" id="profile">
                    <h3 class="head text-center">Deliver the order to my address</h3>
                    <div class="input_field">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-map-marker"></i>
                            </div>
                            @*<textarea type="text" class="form-control" id="Physical_Address" ng-model="PropertyModel.Physical_Address" required ng-minlength="3" ng-maxlength="255" style="min-height:100px; resize:none" placeholder="Physical Address"></textarea>*@
                            <div id="locationField">
                                <input id="autocomplete" name="autocomplete" placeholder="Enter your address here" required class="form-control" onFocus="geolocate()" type="text" style="min-width:360px" />
                            </div>
                            <br />
                            <table id="address">
                                <tr>
                                    <td style="color:black;width:70px"><i>Street</i></td>
                                    <td style="min-width:460px" colspan="2">
                                        <input id="street_number" name="street_number" class="field form-control disabled" required="required" style="max-width:60px" />
                                        <input class="field form-control " id="route" name="street_name" required="required" style="max-width:220px" />
                                    </td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>City</i></td>
                                    <td class="wideField" colspan="3">
                                        <input class="field  form-control" id="locality" name="City" required="required" />
                                    </td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>State</i></td>
                                    <td style="min-width:460px" colspan="2">
                                        <input class="field form-control " id="administrative_area_level_1" name="State" style="max-width:80px" />
                                        &nbsp;&nbsp;&nbsp;
                                        <i>Zip Code</i>
                                        &nbsp;&nbsp;&nbsp;
                                        <input class="field form-control " id="postal_code" name="ZipCode" required="required" style="max-width:102px" />
                                    </td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>Country</i></td>
                                    <td colspan="3">
                                        <input class="field  form-control " name="Country" id="country" />
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>
                                        <input type="submit" value="Continue" class="btn btn-default" />
                                    </td>
                                </tr>
                            </table>

                        </div>

                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
    $(function () {
        $('a[title]').tooltip();
    });
</script>
<script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            @*/** @type {!HTMLInputElement} */*@(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
            document.getElementById(component).value = '';
            document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCA-CuRRycZNmjSB3ilxqrGTcXCxboP_9g&libraries=places&callback=initAutocomplete"
        async defer></script>
<script>
    $(function () {
        var input = document.getElementById("autocomplete");
        var autocomplete = new google.maps.places.Autocomplete(input);

        $('#my-modal').modal('show');

    });

</script>

Funeral Policy/Views/Shopping/Payment_Cancelled.cshtml
@{
    ViewBag.Title = "Payment Cancelled";
}

<h2 class="title text-center">@ViewBag.Title</h2>

<h3>Order Details</h3>

<div class="row">
    <div class="col-md-4">
        <b>Account Details</b>
        @*@{ Funeral_Policy.Models.CartModels.Customer Account = (Funeral_Policy.Models.CartModels.Customer)ViewBag.Account; }*@

        <table class="table">
            <tr>
                <td>Name</td>
                <td>@Account.FirstName   @Account.LastName</td>
            </tr>
            <tr>
                <td>Cell Number</td>
                <td>@Account.phone</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>@Account.Email</td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">

        <b>Order Details</b>
        @*@{ SchoolManagement.Models.CartModels.Order order = (SchoolManagement.Models.CartModels.Order)ViewBag.Order; }*@

        <table class="table">
            <tr>
                <td>Order No.</td>
                <td>@order.Order_ID</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>@order.status</td>
            </tr>

        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4">

        <b>Shipping Details</b>
        @*@{ SchoolManagement.Models.CartModels.Order_Address address = (SchoolManagement.Models.CartModels.Order_Address)ViewBag.Address; }*@
        @if (address != null)
        {
            <table class="table">
                <tr>
                    <td>Street</td>
                    <td>@address.street</td>
                </tr>
                <tr>
                    <td>City/Town</td>
                    <td>@address.city</td>
                </tr>
                <tr>
                    <td>Zipcode</td>
                    <td>@address.zipcode</td>
                </tr>
            </table>
        }
        else
        {
            <hr />
            <p>
                Collect your order at our warehouse.
                <br />
                <i class="fa fa-map-marker"></i>  21 May St, Durban, 4001
                <br />
                <i class="fa fa-clock-o"></i>  8:30 am - 17:00 working hours
                <br />
            </p>
        }

    </div>
    <div class="col-md-6">

        <b>Items in this Order</b>
        <table class="table">
            <tr>
                <th>
                    Picture
                </th>
                <th>
                    Item
                </th>
                <th>
                    Qty
                </th>
                <th>
                    Price
                </th>
            </tr>

            @*@foreach (var item in (List<SchoolManagement.Models.CartModels.Order_Item>)ViewBag.Items)*@
            {
                <tr>
                    <td>
                        @if (item.Item.Picture != null)
                        {
                            var base64 = Convert.ToBase64String(item.Item.Picture);
                            var imgSrc = string.Format("Models:image/gif;base64,{0}", base64);
                            <img src="@imgSrc" width="60" height="70" />
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.quantity)
                    </td>
                    <td>
                        R @Html.DisplayFor(modelItem => item.price)
                    </td>
                </tr>
            }

            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    R @ViewBag.Total
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    @*<a href="@Url.Action("Secure_Payment", "Shopping", new { id = order.Order_ID})" class="btn btn-success"><i class="fa fa-lock"></i> Secure Payment</a>*@
                </td>
            </tr>
        </table>

    </div>
</div>

Funeral Policy/Views/Shopping/Payment_Successfull.cshtml
@{
    ViewBag.Title = "Payment_Successfull";
}

<h2>Payment_Successfull</h2>

Funeral Policy/Views/Shopping/ShoppingCart.cshtml
@model List<Funeral_Policy.Models.CartModels.Cart_Item>

@{
    ViewBag.Title = "Shopping Cart";
}
<h2 class="title text-center">@ViewBag.Title</h2>
<div class="row">

    @using (Html.BeginForm())
    {
        <table class="table">
            <tr style="background: #f3f3f3;">
                <th hidden="hidden"></th>
                <th>Picture</th>
                <th>
                    Name
                </th>
                <th>
                    Availability
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Price
                </th>
                <th></th>
            </tr>

            @for (int item = 0; item < Model.Count(); item++)
            {
                <tr>
                    <td hidden="hidden">
                        @Html.EditorFor(modelItem => Model[item].cart_item_id)
                    </td>
                    <td>
                        @if (Model[item].Item.Picture != null)
                    {
                        var base64 = Convert.ToBase64String(Model[item].Item.Picture);
                        var imgSrc = string.Format("data:image/gif;base64,{0}", base64);
                            <img src="@imgSrc" width="60" height="70" />
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[item].Item.Name)
                    </td>
                    <th>
                        @Model[item].Item.QuantityInStock in stock
                    </th>
                    <td>
                        @Html.EditorFor(modelItem => Model[item].quantity, new { htmlAttributes = new { @class = "form-control", @style="width:100px" } })
                    </td>
                    <th>
                         @Model[item].price.ToString("R 0.00")
                    </th>
                    <td>
                        <a href="@Url.Action("remove_from_cart", "Shopping", new {id = Model[item].cart_item_id})" class="btn btn-default"><i class="fa fa-times"></i> Remove</a>
                    </td>
                </tr>
            }
            <tr>
                <td hidden="hidden"></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    Total:<b> @ViewBag.TotalQTY </b>
                    @if (Model.Count == 0)
                {
                        <input type="submit" value="Update" class="btn btn-default disabled" />
                    }
                    else
                    {
                        <input type="submit" value="Update" class="btn btn-default" />
                    }
                </td>
                <th>
                     @ViewBag.Total.ToString("R 0.00")
                </th>
                <td></td>
            </tr>
            <tr>
                <td hidden="hidden"></td>
                <td></td>
                <td></td>
                <td>
                    <a href="@Url.Action("Index", "Shopping")" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back to Extras</a>
                </td>
                <th>
                    <a href="@Url.Action("Checkout", "Shopping")" class="btn btn-success"><i class="fa fa-lock"></i> Submit order</a>
                </th>
                <td></td>
            </tr>
        </table>

    }
</div>