Funeral Policy/Models/Quote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IdentitySample.Models;

namespace Funeral_Policy.Models
{
    public class Quote
    {
        [Key]
        public int quoteId { get; set; }
        [Required,DisplayName("First Name")]
        public string Name { get; set; }
        [Required, DisplayName("Surname")]
        public string Surname { get; set; }
        [Required]
        public string Gender { get; set; }
        public string MemberEmail { get; set; }
       public int MemberAplicationId { get; set; }
        [Required]
        public int Age { get; set; }
        [Required, DisplayName("cellphone")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "You must provide a phone number")]
        public string Phone { get; set; }
        [DisplayName("Funeral Plan")]
        public int FuneralPlanId { get; set; }
       public virtual FuneralPlan FuneralPlan { get; set; }
        //[Required,DisplayName("Payout")]
        //public int funeralCoverPayoutId { get; set; }
        //public virtual FuneralCoverPayout FuneralCoverPayout { get; set; }
        //public maritalStatus MaritalStatus { get; set; }
        [DisplayName("Quote Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? Quote_Date { get; set; }
        [Required, DisplayName("Monthly Premium"), DataType(DataType.Currency)]
        public decimal PremiumCost { get; set; }
        public string Status { get; set; }
        [DisplayName("Cover Payout"), DataType(DataType.Currency)]
        public double Funeralpayout { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public ICollection<MemberApplication> memberApplications { get; set; }
        public ICollection<FuneralPlan> funeralPlans { get; set; }
        /// public string Email { get; set; }
        ApplicationDbContext db = new ApplicationDbContext();
        public decimal GetFuneralPayout()
        {
            var w = (from e in db.funeralPlans
                     where e.FuneralPlanId == FuneralPlanId
                     select e.FuneralCoverPayout.PayoutAmount).FirstOrDefault();
            return w;
        }

      

        public string GetPlanName()
        {
            var p = (from m in db.funeralPlans
                     where m.FuneralPlanId == FuneralPlanId
                     select m.FuneralPlanName).FirstOrDefault();
            return p;
        }
        public string GetPlanDescription()
        {
            var z = (from v in db.funeralPlans
                     where v.FuneralPlanId == FuneralPlanId
                     select v.FuneralPlanDescription).FirstOrDefault();
            return z;
        }
        public double CalculatePrice()
        {
            // Work out base price.
            // Start with male customers.
            double TotalPremium;

            if (Gender == "Male")
            {
                if (Age >= 0 && Age <= 18)
                {
                    TotalPremium = 150.00;
                }
                else if (Age >= 19 && Age <= 24)
                {
                    TotalPremium = 180.00;
                }
                else if (Age >= 25 && (Age) <= 35)
                {
                    TotalPremium = 200.00;
                }
                else if ((Age) >= 35 && (Age) <= 45)
                {
                    TotalPremium = 250.00;
                }
                else if ((Age) >= 45 && (Age) <= 60)
                {
                    TotalPremium = 320.00;
                }
                else
                {
                    TotalPremium = 500.00;
                }
            }

            //Then look at female customers.
            else
            {
                if (Age >= 0 && Age <= 18)
                {
                    TotalPremium = 100.00;
                }
                else if (Age >= 19 && Age <= 24)
                {
                    TotalPremium = 165.00;
                }
                else if (Age >= 25 && Age <= 35)
                {
                    TotalPremium = 180.00;
                }
                else if (Age >= 35 && Age <= 45)
                {
                    TotalPremium = 225.00;
                }
                else if (Age >= 45 && Age <= 60)
                {
                    TotalPremium = 315.00;
                }
                else
                {
                    TotalPremium = 485.00;
                }
            }

            //    // Adjust Premium based on "Regional Health Index"
            //    switch (client.Country)
            //    {
            //        case "England":
            //            break;

            //        case "Wales":
            //            TotalPremium = TotalPremium - 100.00;
            //            break;

            //        case "Scotland":
            //            TotalPremium = TotalPremium + 200.00;
            //            break;

            //        case "Ireland":
            //            TotalPremium = TotalPremium + 50.00;
            //            break;

            //        case "Northern Ireland":
            //            TotalPremium = TotalPremium + 75.00;
            //            break;

            //        default:
            //            TotalPremium = TotalPremium + 100.00;
            //            break;
            //    }

            //    // If client has children increase premium by 50%
            //    if (client.Children == "Y")
            //    {
            //        TotalPremium = TotalPremium * 1.5;
            //    }

            //    // If client is a smoker increase premium by 300%
            //    if (client.Smoker == "Y")
            //    {
            //        TotalPremium = TotalPremium * 4.0;
            //    }

            //    // Adjust premium based on exercise.
            //    if (client.HoursOfExercise < 1)
            //    {
            //        TotalPremium = TotalPremium * 1.2;
            //    }
            //    else if (client.HoursOfExercise < 3)
            //    {
            //    }
            //    else if (client.HoursOfExercise < 6)
            //    {
            //        double Deduction = TotalPremium * 0.3;
            //        TotalPremium = TotalPremium - Deduction;
            //    }
            //    else if (client.HoursOfExercise < 9)
            //    {
            //        double Deduction = TotalPremium * 0.5;
            //        TotalPremium = TotalPremium - Deduction;
            //    }
            //    else if (client.HoursOfExercise >= 9)
            //    {
            //        TotalPremium = TotalPremium * 1.5;
            //    }

            // Check that the final premium is not less then R50, if it is make the premium R50
            if (TotalPremium < 50.00)
            {
                TotalPremium = 50.00;
            }
            return TotalPremium;
        }


    }

}

Funeral Policy/Controllers/QuotesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Funeral_Policy.Models;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;

namespace Funeral_Policy.Controllers
{
    public class QuotesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private MemberApplicationView membrapp = new MemberApplicationView();
        public ActionResult PlanView(int? id)
        {
            
            var results = db.quotes.ToList();
            if (User.IsInRole("Member"))
            {
               
                 results =results. Where(x => x.MemberEmail == User.Identity.Name).ToList();
                

            }
            return View(results);
        }
        public ActionResult PlanView2(int? id)
        {

            

            var results = db.quotes.ToList();
            if (User.IsInRole("Admin"))
            {



                results = db.quotes.Where(x => x.quoteId==id).ToList();


            }
                return View(results);

             
               
        }

        // GET: Quotes
        public ActionResult Index()
        {
            var kl = db.quotes.ToList();
            if (User.IsInRole("Member"))
            {
                kl = kl.Where(o => o.MemberEmail == User.Identity.Name).ToList();
            }
            return View(kl);
            
        }

        // GET: Quotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            return View(quote);
        }

        // GET: Quotes/Create
        public ActionResult Create()
        {
            
            //ViewBag.funeralCoverPayoutId = new SelectList(db.funeralCoverPayouts, "funeralCoverPayoutId", "PayoutAmount");
            ViewBag.FuneralPlanId = new SelectList(db.funeralPlans, "FuneralPlanId", "FuneralPlanName");
           

            var memberapp = db.MemberApplications.Where(m => m.Email == User.Identity.Name).FirstOrDefault();
            Quote qt = new Quote();
            qt.Name = memberapp.Name;
            qt.Surname = memberapp.Surname;
            qt.Gender = memberapp.Gender;
            qt.Phone = memberapp.Phone;
            qt.MemberAplicationId = memberapp.MemberAplicationId;
            
            //Quote quote = new Quote();
            //quote.PremiumCost = (decimal)c;
            return View(qt);
        }

        // POST: Quotes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "quoteId,Name,Surname,Gender,Age,Phone,FuneralPlanId,Quote_Date,PremiumCost")] Quote quote)
        {
            if (ModelState.IsValid)
            {
                var memberApp = db.MemberApplications.Where(m => m.MemberAplicationId == quote.MemberAplicationId).FirstOrDefault();
                quote.Quote_Date = System.DateTime.Today;
                if (quote.Age <= 0)
                {
                    ViewBag.ErrorData = "Age must be a positive number";
                    return View(quote);
                }
                Quote quote1 = new Quote();
                quote1.MemberAplicationId = quote.MemberAplicationId;
                quote.MemberEmail = User.Identity.Name;
                quote.PlanName = quote.GetPlanName();
                quote.PlanDescription=quote.GetPlanDescription();
                quote.Funeralpayout = (double)quote.GetFuneralPayout();
                quote.PremiumCost = Convert.ToDecimal(quote.CalculatePrice());
                db.quotes.Add(quote);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.funeralCoverPayoutId = new SelectList(db.funeralCoverPayouts, "funeralCoverPayoutId", "PayoutAmount", quote.funeralCoverPayoutId);
            ViewBag.FuneralPlanId = new SelectList(db.funeralPlans, "FuneralPlanId", "FuneralPlanName", quote.FuneralPlanId);
            return View(quote);
        }
        public ActionResult QuoteAccept(int? id)
        {
            MemberApplication memberApplication = db.MemberApplications.Find(id);
            if (memberApplication.Status == "Incomplete" || memberApplication.Status == "Complete")
            {
               TempData["AlertMessage"] = "The application has been is completed";
               //  return RedirectToAction("QuoteAccept", "Quotes");
            }
            else
            {
                
                var username = User.Identity.GetUserName();
                memberApplication.PremiumCost = memberApplication.PremiumCost;
                
                memberApplication.Status = "Completed";
                db.Entry(memberApplication).State = EntityState.Modified;

                db.SaveChanges();

                //EmailService service = new EmailService();
                //string message = "Hi " + memberApplication.Tittle + " " + memberApplication.Surname + "\n your application for funeral has been approved, please login to accept policy. \n Kind Regards, \n Heavenly Sent Funerals";
                //service.CaptureEmail(memberApplication.Email, "Membership Application Approved", message);


            };

            // return RedirectToAction("Index2");
            return View();
        }




        // GET: Quotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            //ViewBag.funeralCoverPayoutId = new SelectList(db.funeralCoverPayouts, "funeralCoverPayoutId", "PayoutAmount", quote.funeralCoverPayoutId);
            ViewBag.FuneralPlanId = new SelectList(db.funeralPlans, "FuneralPlanId", "FuneralPlanName", quote.FuneralPlanId);
            return View(quote);
        }

        // POST: Quotes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "quoteId,Name,Surname,Gender,Age,Phone,FuneralPlanId,Quote_Date,PremiumCost")] Quote quote)
        {
            if (ModelState.IsValid)
            {
               

                db.Entry(quote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.funeralCoverPayoutId = new SelectList(db.funeralCoverPayouts, "funeralCoverPayoutId", "PayoutAmount", quote.funeralCoverPayoutId);
            ViewBag.FuneralPlanId = new SelectList(db.funeralPlans, "FuneralPlanId", "FuneralPlanName", quote.FuneralPlanId);
            return View(quote);
        }

        // GET: Quotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            return View(quote);
        }

        // POST: Quotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quote quote = db.quotes.Find(id);
            db.quotes.Remove(quote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Funeral Policy/Views/Quotes/Create.cshtml
@model Funeral_Policy.Models.Quote

@{ ViewBag.Title = "Create"; }

<div class="form-horizontal">
    <h4><b>Before we finish your application, Choose your Prefered funeral Plan.</b></h4>
    <br />
    @*<style>
        body {
            text-align: center;
        }

        form {
            display: inline-grid;
        }
    </style>*@
    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <p>No commitment until you accept your policy.</p>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <b> @Html.DisplayFor(model => model.Name)</b>
            @Html.HiddenFor(model => model.Name)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <b> @Html.DisplayFor(model => model.Surname)</b>
            @Html.HiddenFor(model => model.Surname)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <b> @Html.DisplayFor(model => model.Gender)</b>
            @Html.HiddenFor(model => model.Gender)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <b> @Html.DisplayFor(model => model.Phone)</b>
            @Html.HiddenFor(model => model.Phone)
        </div>
    </div>




    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.FuneralPlanId, "Funeral Plan", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("FuneralPlanId", null, "--Please Select--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FuneralPlanId, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.funeralCoverPayoutId, "funeral Cover Payout", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("funeralCoverPayoutId", null, "--Please Select--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.funeralCoverPayoutId, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.Quote_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quote_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quote_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PremiumCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PremiumCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PremiumCost, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-success" />
            <br />
            <br />
            We won't share your information with anyone unlawfully
        </div>
    </div>
</div>}
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Funeral Policy/Views/Quotes/Delete.cshtml
@model Funeral_Policy.Models.Quote

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Quote</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.FuneralPlan.FuneralCoverPayout)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuneralPlan.FuneralCoverPayout)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.FuneralPlan.FuneralPlanName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuneralPlan.FuneralPlanName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quote_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quote_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PremiumCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PremiumCost)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Funeral Policy/Views/Quotes/Details.cshtml
@model Funeral_Policy.Models.Quote

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Quote</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.FuneralPlan.FuneralCoverPayout)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuneralPlan.FuneralCoverPayout)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.FuneralPlan.FuneralPlanName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuneralPlan.FuneralPlanName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quote_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quote_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PremiumCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PremiumCost)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.quoteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Funeral Policy/Views/Quotes/Index.cshtml
@model IEnumerable<Funeral_Policy.Models.Quote>
@{ ViewBag.Title = "Index"; }
@*<style>
    body {
        text-align: center;
    }
    form {
        display: inline-block;
    }*@
    <!--</style>-->
<html>
<!--<head>-->
    @*<style>
        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size:50px;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }
    </style>*@
    <!--</head>-->
    <body>
        <center>
            @*<div style="background-color:whitesmoke; height:37px;width:85% ;font-size:15px;">*@
                <h2>You qualify for Heavenly Sent Funeral Cover.</h2>
                <hr />
                <br />
                @*<div class="card shadow mb-4" style="background-color:aliceblue; width:85%;font-size:12px; top:auto">*@
                    <div class="card-header ">

                        <div class="row">
                            @foreach (var item in Model)
                            {
                <div class="col-md-3">
                    <div class="container">


                        <p class="card-text">
                            <b> Name :</b>
                            @Html.DisplayFor(modelItem => item.Name)
                        </p>
                        <p class="card-text">
                            <b>Surname :</b>
                            @Html.DisplayFor(modelItem => item.Surname)
                        </p>
                        <p class="card-text">
                            <b>Gender :</b>
                            @Html.DisplayFor(modelItem => item.Gender)
                        </p>

                        <p class="card-text">
                            <b>Funeral Plan :</b>
                            @Html.DisplayFor(modelItem => item.PlanName)
                        </p>
                        <p class="card-text">
                            <b>Payout amount:</b>
                            @Html.DisplayFor(modelItem => item.Funeralpayout)
                        </p>
                        <p class="card-text">
                            <b>Description:</b>
                            @Html.DisplayFor(modelItem => item.PlanDescription)
                        </p>
                        <p class="card-text">
                            <b>Monthly Premium:</b>
                            @Html.DisplayFor(modelItem => item.PremiumCost)
                        </p>
                        

                    <a href='@Url.Action("QuoteAccept", "Quotes", new { id = item.quoteId, holder = ViewBag.Holder }, null)' class="btn btn-success">Accept quote</a>
                        
                                    </div>
                </div>}
                        </div>

                        <br />

                    </div>
                @*</div>
                </div>*@
                </center>

</body>
</html>

Funeral Policy/Views/Quotes/QuoteAccept.cshtml
@{
    ViewBag.Title = "QuoteAccept";
}

<div style="text-align:center; font-weight:bold; font-size: 50px;">
    Application Succesfully Submitted<br />
    <span style="color:green">Thank you for accepting your quote and submitting you application . We will thoroughly revise your application for approval.</span>
</div>